main: com.excavator.PixelEvents.Main
name: PixelEvents
version: 2.0
author: Excavator#9612

commands:
  event:
    usage: /<command> <start | stop | help | revive> [player]
    description: Custom PixelEvents Plugin
    permission: pixelevents.event
    permission-message: No permission!
permissions:
  pixelevents.event:
   description: PixelEvents permission
   default: false
    